[package]
name = "actix-web-serve"
version = "0.1.0"
authors = ["Eon S. Jeon <esjeon@hyunmu.am>"]
edition = "2018"

[dependencies]
actix="0.7.0"
env_logger="0.6.0"

[dependencies.actix-web]
git="https://github.com/actix/actix-web"
branch="0.8"
